export const JobActionTypes = {
    JOB_LIST :'JOB_LIST',
    ADD_JOB : 'ADD_JOB',
    TOGGLE_HIDDEN : 'TOGGLE_HIDDEN',
    SELECT_ITEM : 'SELECT_ITEM',
    REMOVE_ITEM : 'REMOVE_ITEM',
    SELECT_JOB_DETAIL: 'SELECT_JOB_DETAIL'
}

